### PR TITLE
Jc web speech

### PR DESCRIPTION
**Pull request by jordan-castelloe**
Added speaker module that sets up a SpeechSynthesis API and feeds it into the events module so that when you click the "listen" button it reads the text // still doesn't speak Japanese, though

### CODE REVIEW

**Comment by DavidLarsKetch** [comment]
:-1:

Looks like @kirbyclark's most recent PR is now causing some conflicts with `events.js`. Just to reprint the workflow:
- In `master`: `pull origin master`
- `git checkout jc-web-speech`
- `git merge master`
- Then you'll get a merge conflict warning
- Open those files, resolve conflicts, save
- `git add [files-with-resolved-conflicts]`
- `git checkin -m "[yay, some commit message]"`
- `git push origin jc-web-speech`

Boom, roasted.

**Comment by DavidLarsKetch** [comment]
Also, I guess it'll be best to keep the `voice[n]` be the same as `lang` (I think it was `voice[1]`?) so it doesn't try to switch voices on us until we can figure out how to get the dang voice in there.

**Comment by jordan-castelloe** [comment]
@DavidLarsKetch merge conflicts fixed! Appropriate voices added! Callback function figured out! Boom, UNROASTED

**Comment by hunterphillips** [comment]
👍

**Pull request merged**
